#pragma once

typedef enum status_e {
    STATUS_BOOT,
    STATUS_SYNCED,
    STATUS_INIT,
    STATUS_READY,

    STATUS_CAM_INIT_FAIL,
    STATUS_NO_WIFI_CONN,
    STATUS_NO_SDC,
    STATUS_CONFIG_FILE_NOT_CREATED,
    STATUS_BAD_WIFI_CONF,
    STATUS_NO_INTERNET,
    STATUS_NO_API_URL,

    STATUS_ERROR = -1
} status_t;

#define LED_COUNT 8
